// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgPbQNQb99AFj6NFQ3kpdtCW-i2uwWcg',
    appId: '1:929019006788:android:c4cac947b0ecd43d6d5111',
    messagingSenderId: '929019006788',
    projectId: 'cs-100',
    storageBucket: 'cs-100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05IDb-DoWCyrfAchPY_xhksVmG0TONUY',
    appId: '1:929019006788:ios:34b1e41cdf27132d6d5111',
    messagingSenderId: '929019006788',
    projectId: 'cs-100',
    storageBucket: 'cs-100.appspot.com',
    androidClientId: '929019006788-0ecmkonp8ptg3fr34kn98ga8dh5hhvfq.apps.googleusercontent.com',
    iosClientId: '929019006788-h76f4r7j70s0evvsru1gj47u1amj772v.apps.googleusercontent.com',
    iosBundleId: 'com.jerondev.auth',
  );
}
